# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtQUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(349, 361)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.number_e = QtWidgets.QLCDNumber(self.centralwidget)
        self.number_e.setGeometry(QtCore.QRect(50, 50, 211, 91))
        self.number_e.setMaximumSize(QtCore.QSize(211, 151))
        self.number_e.setStyleSheet("font: 20pt \"Impact\";\n"
"color: rgb(255, 255, 255);")
        self.number_e.setFrameShape(QtWidgets.QFrame.Panel)
        self.number_e.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.number_e.setObjectName("number_e")
        self.use_e = QtWidgets.QPushButton(self.centralwidget)
        self.use_e.setGeometry(QtCore.QRect(50, 150, 51, 31))
        self.use_e.setStyleSheet("font: 8pt \"Impact\";\n"
"border-color: rgb(255, 255, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"color: rgb(255, 0, 0);\n"
"")
        self.use_e.setObjectName("use_e")
        self.gain_e = QtWidgets.QPushButton(self.centralwidget)
        self.gain_e.setGeometry(QtCore.QRect(210, 150, 51, 31))
        self.gain_e.setStyleSheet("font: 8pt \"Impact\";\n"
"color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"")
        self.gain_e.setObjectName("gain_e")
        self.destroy_e = QtWidgets.QPushButton(self.centralwidget)
        self.destroy_e.setGeometry(QtCore.QRect(130, 150, 51, 31))
        self.destroy_e.setStyleSheet("font: 8pt \"Impact\";\n"
"color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"")
        self.destroy_e.setObjectName("destroy_e")
        self.number_c = QtWidgets.QLCDNumber(self.centralwidget)
        self.number_c.setGeometry(QtCore.QRect(50, 190, 121, 111))
        self.number_c.setMaximumSize(QtCore.QSize(121, 111))
        self.number_c.setStyleSheet("font: 20pt \"Impact\";\n"
"color: rgb(255, 255, 255);")
        self.number_c.setFrameShape(QtWidgets.QFrame.Panel)
        self.number_c.setObjectName("number_c")
        self.destroy_c = QtWidgets.QPushButton(self.centralwidget)
        self.destroy_c.setGeometry(QtCore.QRect(180, 230, 51, 31))
        self.destroy_c.setStyleSheet("font: 8pt \"Impact\";\n"
"background-color: rgb(255, 255, 0);")
        self.destroy_c.setObjectName("destroy_c")
        self.use_c = QtWidgets.QPushButton(self.centralwidget)
        self.use_c.setGeometry(QtCore.QRect(180, 190, 51, 31))
        self.use_c.setStyleSheet("font: 8pt \"Impact\";\n"
"background-color: rgb(255, 255, 0);")
        self.use_c.setObjectName("use_c")
        self.gain_c = QtWidgets.QPushButton(self.centralwidget)
        self.gain_c.setEnabled(True)
        self.gain_c.setGeometry(QtCore.QRect(180, 270, 51, 31))
        self.gain_c.setStyleSheet("font: 8pt \"Impact\";\n"
"background-color: rgb(255, 255, 0);")
        self.gain_c.setCheckable(False)
        self.gain_c.setObjectName("gain_c")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, -10, 351, 341))
        self.label_3.setMouseTracking(False)
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/Downloads/axie.png);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/Downloads/axie.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 0, 171, 51))
        self.label.setStyleSheet("font: 28pt \"Impact\";\n"
"color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.gain_et = QtWidgets.QPushButton(self.centralwidget)
        self.gain_et.setGeometry(QtCore.QRect(270, 80, 51, 31))
        self.gain_et.setStyleSheet("font: 8pt \"Impact\";\n"
"")
        self.gain_et.setObjectName("gain_et")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(280, 140, 61, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 160, 61, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(280, 180, 61, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3.raise_()
        self.number_e.raise_()
        self.use_e.raise_()
        self.gain_e.raise_()
        self.destroy_e.raise_()
        self.number_c.raise_()
        self.destroy_c.raise_()
        self.use_c.raise_()
        self.gain_c.raise_()
        self.label.raise_()
        self.gain_et.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 349, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.destroy_e.clicked.connect(self.preview_md) # type: ignore
        self.gain_e.clicked.connect(self.preview_p) # type: ignore
        self.use_e.clicked.connect(self.preview_m) # type: ignore
        self.destroy_c.clicked.connect(self.preview_cm) # type: ignore
        self.gain_c.clicked.connect(self.preview_cp) # type: ignore
        self.use_c.clicked.connect(self.preview_cm) # type: ignore


        self.gain_et.clicked.connect(self.endturn) # type: ignore
        self.gain_et.clicked.connect(self.lineEdit.clear) # type: ignore
        self.gain_et.clicked.connect(self.lineEdit_2.clear) # type: ignore
        self.gain_et.clicked.connect(self.lineEdit_3.clear) # type: ignore
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.count = 3
        self.number_e.display(self.count)
        self.count_c = 6
        self.number_c.display(self.count_c)
        self.show_use = 0
        self.show_destroy = 0
        self.show_gain = 0
        self.count1 = 0
        self.count2 = 0
        self.count3 = 0
        self.round = 1
    def preview_p(self):
        if self.count == 10:
            self.count = 10
        else:
            self.count += 1
        self.number_e.display(self.count)
        self.count3 += 1
        strcount3 = 'Gain : {}'.format(self.count3)
        self.lineEdit_3.setText(strcount3)
    def preview_m(self):
        if self.count == 0:
            self.count = 0
        else:
            self.count -= 1
        self.number_e.display(self.count)
        self.count1 += 1
        strcount1 = 'Use : {}'.format(self.count1)
        self.lineEdit.setText(strcount1)
    def preview_cp(self):
        if self.count_c == 12:
            self.count_c = 12
        else:
            self.count_c += 1
        self.number_c.display(self.count_c)
    def preview_cm(self):
        if self.count_c == 0:
            self.count_c = 0
        else:
            self.count_c -= 1
        self.number_c.display(self.count_c)

    def preview_md(self):
        if self.count == 0:
            self.count = 0
        else:
            self.count -= 1
        self.number_e.display(self.count)
        self.count2 += 1
        strcount2 = 'Destroy : {}'.format(self.count2)
        self.lineEdit_2.setText(strcount2)

    def endturn(self):
        if self.count >= 10 and self.count_c >= 12:
           self.count = 10
           self.count_c = 12
        elif self.count < 10 and self.count_c == 12:
           self.count_c = 12
           self.count += 2
        elif self.count == 10 and self.count_c < 12:
           self.count = 10
           self.count_c += 3
        elif self.count < 10 and self.count_c < 12:
           self.count += 2
           self.count_c += 3
        self.number_c.display(self.count_c)
        self.number_e.display(self.count)
        _translate = QtCore.QCoreApplication.translate
        self.round += 1 
        round = 'Round: {}'.format(self.round)
        self.label.setText(_translate("MainWindow",round))
        self.count1 = 0
        self.count2 = 0
        self.count3 = 0
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Axie Calculator"))
        self.use_e.setText(_translate("MainWindow", "Use"))
        self.gain_e.setText(_translate("MainWindow", "Gain "))
        self.destroy_e.setText(_translate("MainWindow", "Destroy"))
        self.destroy_c.setText(_translate("MainWindow", "Destroy"))
        self.use_c.setText(_translate("MainWindow", "Use"))
        self.gain_c.setText(_translate("MainWindow", "Gain "))
        self.label.setText(_translate("MainWindow", "Round: 1"))
        self.gain_et.setText(_translate("MainWindow", "End Turn"))
import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
